# Generated by Django 5.1.1 on 2024-09-16 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('phone_number', models.CharField(max_length=20)),
                ('address_number', models.CharField(max_length=200)),
                ('address_street', models.CharField(max_length=200)),
                ('address_city', models.CharField(max_length=200)),
                ('address_state', models.CharField(max_length=200)),
                ('address_zip', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
