# Generated by Django 5.1.1 on 2024-10-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cart_food_price_cart_movie_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='food_price',
            new_name='food_total',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='movie_price',
            new_name='movie_adult_quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='movie_quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='movie_child_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='movie_senior_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='movie_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
